language: cpp
compiler:
    - g++-6
    - clang++-3.8
script  : 
    - if [ "$CXX" = "g++" ]; then export CXX="g++-6"; fi
    - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8"; fi
    - make
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
        packages:
            - clang-3.8
            - g++-6
